### PR TITLE
A sample JAX-RS resource implementation and its test

### PR DESCRIPTION
**Pull request by nikospara**
The `GameResource`, its implementation, connected to the `GameService` and a very basic approach for testing resources in isolation. In contrast, quarkus-test runs the entire container, so is more appropriate for integration tests IMO (see branch experiments-quarkus-test).

The purpose of REST-layer unit tests is to ensure correct setup of the JAX-RS environment, e.g. correct serialization and deserialization, correct communication with the business logic components etc.

### CODE REVIEW

**Review by nomikosi — APPROVED** [review]
approved, nothing to note

**Comment by nomikosi** [comment]
approved

**Comment by NikolaosZervas** [comment]
Hello team!
I try to build the master but I got this errors.
What should I do???

Failed to execute goal io.quarkus:quarkus-maven-plugin:0.21.2:build
(default) on project nanithing-web: Failed to build a runnable JAR: Failed
to build a runner jar: Failed to augment application classes: Build
failure: Build failed due to errors
[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw
an exception: javax.enterprise.inject.spi.DeploymentException: Found 3
deployment problems:
[1] Unsatisfied dependency for type
nanithing.services.authorization.Authorization and qualifiers [@Default]
- java member: nanithing.services.impl.GameServiceImpl#<init>()
- declared on CLASS bean [types=[nanithing.services.GameService,
java.lang.Object, nanithing.services.impl.GameServiceImpl],
qualifiers=[@Default, @Any], target=nanithing.services.impl.GameServiceImpl]
[2] Unsatisfied dependency for type
nanithing.services.impl.GameAuthorization and qualifiers [@Default]
- java member: nanithing.services.impl.GameServiceImpl#<init>()
- declared on CLASS bean [types=[nanithing.services.GameService,
java.lang.Object, nanithing.services.impl.GameServiceImpl],
qualifiers=[@Default, @Any], target=nanithing.services.impl.GameServiceImpl]
[3] Unsatisfied dependency for type nanithing.dao.GameDao and qualifiers
[@Default]
- java member: nanithing.services.impl.GameServiceImpl#<init>()
- declared on CLASS bean [types=[nanithing.services.GameService,
java.lang.Object, nanithing.services.impl.GameServiceImpl],
qualifiers=[@Default, @Any], target=nanithing.services.impl.GameServiceImpl]
at
io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:843)
at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:214)
at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:249)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:768)
at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
at
org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
at
org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
at
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
at
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
at java.base/java.lang.Thread.run(Thread.java:834)
at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException:
Unsatisfied dependency for type
nanithing.services.authorization.Authorization and qualifiers [@Default]
- java member: nanithing.services.impl.GameServiceImpl#<init>()
- declared on CLASS bean [types=[nanithing.services.GameService,
java.lang.Object, nanithing.services.impl.GameServiceImpl],
qualifiers=[@Default, @Any], target=nanithing.services.impl.GameServiceImpl]
at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:428)
at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:371)
at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:206)
... 14 more
Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException:
Unsatisfied dependency for type nanithing.services.impl.GameAuthorization
and qualifiers [@Default]
- java member: nanithing.services.impl.GameServiceImpl#<init>()
- declared on CLASS bean [types=[nanithing.services.GameService,
java.lang.Object, nanithing.services.impl.GameServiceImpl],
qualifiers=[@Default, @Any], target=nanithing.services.impl.GameServiceImpl]
at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:428)
at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:371)
at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:206)
... 14 more
Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException:
Unsatisfied dependency for type nanithing.dao.GameDao and qualifiers
[@Default]
- java member: nanithing.services.impl.GameServiceImpl#<init>()
- declared on CLASS bean [types=[nanithing.services.GameService,
java.lang.Object, nanithing.services.impl.GameServiceImpl],
qualifiers=[@Default, @Any], target=nanithing.services.impl.GameServiceImpl]
at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:428)
at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:371)
at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:206)
... 14 more
-> [Help 1]

Στις Κυρ, 22 Σεπ 2019 στις 7:59 μ.μ., ο/η nomikosi <notifications@github.com>
έγραψε:

**Comment by nikospara** [comment]
Niko,

Indeed there are dependencies missing, we need to take care of authentication/authorization.

Check out the [dao](https://github.com/nikospara/nanithing-back/tree/dao) branch (with the latest fixes), it contains a dummy implementation of the missing services and compiles & runs successfully.

**Comment by nikospara** [comment]
By the way, authentication/authorization is the next topic to be implemented, before we have a functional application (with extremely limited functionality). Then we have to check some non-functional aspects: documentation (`mvn site` maybe?), integration with Travis for building, and SonarQube for code metrics.

**Comment by NikolaosZervas** [comment]
Thanks Nikos,

I will take a look then to the dao branch! Architecture is very clear at
the moment and I think I could easily add things!
Thanks!!

Στις Δευ, 23 Σεπ 2019 στις 9:32 μ.μ., ο/η Nikos Paraskevopoulos <
notifications@github.com> έγραψε:

**Pull request merged**
